project:
  type: website

website:
  title: "Documentation PMSISoft"
  description: "Documentation et support du logiciel PMSISoft, analyse PMSI MCO, SMR, PSY et HAD"
  site-url: https://www.pmsisoft.com
  navbar:
    background: "#447099"
    right: 
      - text: "Accès"
        menu:
          - href: "acces_pmsisoft_mco.qmd"
            text: "PMSISoft MCO"
          - href: "acces_pmsisoft_ssr.qmd"
            text: "PMSISoft SMR"
          - href: "acces_pmsisoft_psy.qmd"
            text: "PMSISoft PSY"
          - href: "acces_pmsisoft_had.qmd"
            text: "PMSISoft HAD"        
      - text: "Contact"
        href: https://www.lespmsi.com/a-propos-2
      - icon: github
        href: https://github.com/denisGustin/datapmsi
  sidebar: 
    style: docked
    contents: 
      - href: documentation_mco.qmd
        text: "Documentation MCO"
      - href: documentation_smr.qmd
        text: "Documentation SMR"
      - href: documentation_psy.qmd
        text: "Documentation PSY"
  page-footer:
    left: "Blog codé avec [Quarto](https://quarto.org/)"
    right: "[Mentions légales](../about.html) | &copy; Copyright 2023-2024 - DATAMIS"
    
format:
  html:
    theme: 
      - cosmo
      - style.css
      - theme.scss
    toc: true
    toc-location: "left"
