project:
  type: website

website:
  title: "Documentation PMSISoft"
  description: "Documentation et support du logiciel PMSISoft, analyse PMSI MCO, SSR, PSY et HAD."
  navbar:
    background: "#447099"
    right:
      - text: "Accès"
        menu:
          - href: "acces_pmsisoft_mco.qmd"
            text: "PMSISoft MCO"
          - href: "acces_pmsisoft_ssr.qmd"
            text: "PMSISoft SMR"
          - href: "acces_pmsisoft_psy.qmd"
            text: "PMSISoft PSY"
          - href: "acces_pmsisoft_had.qmd"
            text: "PMSISoft HAD"
      - text: "Contact"
        href: https://www.lespmsi.com/a-propos-2
      - icon: github
        href: https://github.com/denisGustin/pmsisoft-support
    left: 
      - text: "MCO"
        menu:
          - href: "ecrans_mco.qmd"
            text: "Ecrans MCO"
      - text: "SMR"
        menu:
          - href: "ecrans_ssr.qmd"
            text: "Ecrans SMR"
          - href: "liste_analyse_smr.qmd"
            text: "Analyses SMR"
      - text: "PSY"
        menu:
          - href: "ecrans_psy.qmd"
            text: "Ecrans PSY"
  page-footer:
    left: "Blog codé avec [Quarto](https://quarto.org/)"
    right: "&copy; Copyright 2023-2024, [DATAMIS](https://www.lespmsi.com/a-propos-2)"

format:
  html:
    theme: 
      - style.css
      - theme.scss
    toc: true
    toc-depth: 4
    toc-location: "left"